### PR TITLE
Enable `comma-dangle` always-multiline

### PR DESCRIPTION
**Pull request by oktapodia**
Adds a rule to enforce dangling commas 

Trailing commas simplify adding and removing items to objects and arrays, since only the lines you are modifying must be touched. (And then, improve the number of line of codes in a review)

### CODE REVIEW

**Comment by alixeb** [comment]
Personally I don't like trailing comma, but this is for Node linting rules, so whatever B/E devs feel they want to do :D

**Comment by oktapodia** [comment]
@antony Easier during a review either, you will only have 1 line modified instead of 2

**Comment by antony** [comment]
@alixeb being as consistent as possible across front and back end would probably benefit the team though...

**Comment by antony** [comment]
@oktapodia to this day a comma diff has never bothered me - dangling ones in my editor are far more distracting :)

**Comment by makevoid** [comment]
2-1 for now ⚔️

**Comment by mirek** [comment]
nope.

**Comment by antony** [comment]
Closing due to age + majority of no votes

**Pull request closed without merging**
