### PR TITLE
added some rules for arrow functions

### PR DESCRIPTION
**Pull request by jorgemmsilva**
added the following rules:

 - `'arrow-body-style': [ error, 'as-needed']`

https://eslint.org/docs/rules/arrow-body-style#as-needed

 - `'arrow-parens': [ error, 'as-needed']`

https://eslint.org/docs/rules/arrow-parens#as-needed

 - `'arrow-spacing': [ error, { 'before': true, 'after': true }]`

https://eslint.org/docs/rules/arrow-spacing#rule-details

all of them are fixable with `--fix`

___

[](https://api.gh-polls.com/poll/01CMHQ4SE4BQCB9FE98YF91RBB/yes/vote)
[](https://api.gh-polls.com/poll/01CMHQ4SE4BQCB9FE98YF91RBB/no/vote)

### CODE REVIEW

**Comment by shariffy** [comment]
Great call to open a PR! Would be even greater if you could include:
- a poll (a must)
- before / after code snippets
- whether the rule change is fixable with `—fix`

Please see previous PRs for inspiration.

**Comment by shariffy** [comment]
I know this is React and not node but I would like to vote No as I'm fairly strongly against these rules:
https://eslint.org/docs/rules/arrow-body-style#as-needed
https://eslint.org/docs/rules/arrow-parens#as-needed

Every time code needs to be extended, you have to think about what the braces are, potentially put them in (which you have to undo if you were just experimenting). Pretty frustrating.

Same with parens: put them in, remove them... Plus, I really don't find omitting parens more readable. Functions have a certain "shape", when omitted my brain often pauses some ms to parse that it is a param right there.

It all seems like a waste of brain cycles and keystrokes to me - *for what benefit?* If someone cares to explain what I'm not getting... and change my mind/vote.

**Comment by dpbricher** [comment]
I more or less agree with @shariffy. However, I also ignore all of the linting rules when coding and then just run `eslint --fix` before committing, so I'm actually wondering if certain people's dislike of particular rules (that work with `--fix` of course) even really matters 🤔.

It is maybe worth instead asking 'will the code look nicer/more consistent after linting with this rule?', and I think the answer is probably 'yes'. Not sure if that is the general feeling is regarding linting rules here or not though.

**Comment by jorgemmsilva** [comment]
@shariffy imho linting rules should not be a concern when developing.
We should make the IDE work for us, and have it enforcing linting rules when we save a file.

That way you don't need to concern yourself with style while coding, only content.  :)

in VScode, this can be enabled by using the option: ``  "eslint.autoFixOnSave": false

in VIM, a plugin like this should be able to handle it: https://github.com/w0rp/ale

**Comment by shariffy** [comment]
@dpbricher Using `eslint --fix` like `gofmt` has some appeal, I agree, but (if you have linting in your editor) don't you have to keep track of what errors will be sorted out by `eslint --fix` and what you should sort out while you have that file open? That seems like another form of masochism to me. :)

@jorgemmsilva Ok, `autoFixOnSave` could mitigate that to a point, I see.

**Comment by shariffy** [comment]
@jorgemmsilva Also, as an aside, I guess I'm not really into "IDE doing work for me" - battle scars from my Eclipse days, trying to be clever but slow, sorry. To me it sounds like "let's do something complex... (some time later) this is cumbersome, let me write some software to make it easier... hey, everybody else, please use this extra software to make my decision work", which Moore's law supports but maybe let's let simple things be simple? I'd rather be in that camp if I can help it.

**Comment by jorgemmsilva** [comment]
I'm just recommending it, because enabling that option changed my view regarding linting rules.
My code started to be a lot more clean and consistent without any extra work, so I started to embrace auto-fixable linting rules.

I think having this kind of well define standards is better for everyone in the long run, as the codebase tends to get more consistent over time.

**Comment by dpbricher** [comment]
@shariffy no I don't keep track because `--fix` rarely fails. I also haven't automated a solution for that reason (plus that I am too lazy), but I probably should.

I'm inclined to take @jorgemmsilva view on linting, but that might be because I disliked our current linting rules from day one and so would much rather make it my software's problem instead of mine 😅

**Comment by shariffy** [comment]
Thanks for sharing your views @jorgemmsilva and @dpbricher. It's been interesting... :)

**Pull request closed without merging**
