### PR TITLE
Enforce spacing in braces

### PR DESCRIPTION
**Pull request by simontabor**
Spaces around braces improves readability a lot. We seem to be inconsistent with this so need to make a decision regardless.

See https://eslint.org/docs/rules/object-curly-spacing

[](https://api.gh-polls.com/poll/01C7BWTXCWEXW936R326CEDM8Q/Yes/vote)
[](https://api.gh-polls.com/poll/01C7BWTXCWEXW936R326CEDM8Q/No/vote)
[](https://api.gh-polls.com/poll/01C7BWTXCWEXW936R326CEDM8Q/Abstain/vote)

### CODE REVIEW

**Comment by mayk93** [comment]
I agree. Spaces make everything clearer. Not just in this context.

**Comment by simontabor** [comment]
I've just added array-bracket-spacing too as it's very similar to object-curly-spacing

https://eslint.org/docs/rules/array-bracket-spacing

This PR now means we will write
```js
// object-curly-spacing
const thing = { hi: 'everyone' }
const badThing = {hi: 'everyone'}

// array-bracket-spacing
const things = [ 1, 2, 3 ]
const badThings = [1, 2, 3]

// array-bracket-spacing objectsInArrays
// this one is debatable but relatively minor/uncommon
const objectInArray = [{
  hi: 'everyone'
}]
const badObjectInArray = [ {
  hi: 'everyone'
} ]
```

**Comment by antony** [comment]
Makes sense to have both for consistency :+1:

**Comment by antony** [comment]
I feel like this can be merged when you fancy it @simontabor. If you do the following:

```bash
npm version minor
git push && git push --tags
```

Circle will create and publish a new minor release of the library you can start using immediately.

**Comment by simontabor** [comment]
🎉 v1.4.0 released

**Pull request merged**
